#!/usr/bin/env python3
"""
build.py — compile the layered skill hub into single-file bundles that a chat LLM
(ChatGPT, Gemini, Claude, …) can load with ONE fetch or ONE paste.

Outputs (all generated — never edit by hand):

  bundle/HARNESS.md            kernel + module index + ALWAYS-ON modules (the file to fetch/paste)
  bundle/HARNESS-FULL.md       everything: kernel + index + every module with all references
  bundle/modules/<name>.md     one file per module: SKILL.md + all its references (on-demand fetch)
  bundle/pipelines/<name>.md  generated multi-module pipeline packs (one Web-first fetch)
  bundle/manifest.json         machine-readable index
  docs/skill-registry.md       human-readable index (same data)

Source of truth: harness.json (config), VERSION, kernel/KERNEL.md, and every <layer>/<name>/SKILL.md.

Usage:  python3 scripts/build.py [repo_root]         write outputs
        python3 scripts/build.py --check [repo_root] exit 1 if outputs on disk are stale
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import skills_lib as L  # noqa: E402

GEN_NOTE = "<!-- GENERATED by scripts/build.py from the repository sources. Do not edit; edit the source files and rebuild. -->"


# ---------- collection ----------

def collect(root):
    cfg = L.load_config(root)
    version = L.read_version(root)
    skills = []
    for path in sorted(L.find_skill_files(root, cfg["layers"])):
        s = L.load_skill(path, root)
        if s["errors"]:
            raise SystemExit(f"{s['rel']}: {s['errors'][0]} — run validate_skills.py first")
        skills.append(s)
    order = {l: i for i, l in enumerate(cfg["layers"])}
    skills.sort(key=lambda s: (order.get(s["layer"], 99), 0 if s["metadata"].get("load") == "always" else 1, s["name"]))
    return cfg, version, skills


def raw_base(cfg):
    return f"https://raw.githubusercontent.com/{cfg['repo']}/{cfg['branch']}/"


def tree_url(cfg, rel_dir):
    return f"https://github.com/{cfg['repo']}/tree/{cfg['branch']}/{rel_dir}"


# ---------- rendering ----------

def render_module(s, cfg, version, only_files=None):
    """
    One module as a single markdown document.
    only_files: optional list like ["SKILL.md", "references/x.md"] to include a subset (used for always-on core).
    """
    md = s["metadata"]
    files = only_files or (["SKILL.md"] + s["references"])
    parts = [
        f"# MODULE: {s['name']}",
        f"layer: {s['layer']} · load: {md.get('load')} · status: {md.get('status')} · module version: {md.get('version', '?')} · harness {version}",
        f"source: {tree_url(cfg, s['rel_dir'])}",
        "",
        f"**description:** {s['description']}",
        "",
    ]
    if "SKILL.md" in files:
        parts.append(L.demote_headings(s["body"], 1).rstrip())
        parts.append("")
    for ref in files:
        if ref == "SKILL.md":
            continue
        p = os.path.join(s["dir"], ref)
        if not os.path.exists(p):
            raise SystemExit(f"{s['rel_dir']}: missing {ref}")
        content = open(p, encoding="utf-8").read()
        parts.append("---")
        parts.append("")
        parts.append(f"## Reference: {ref}")
        parts.append("")
        parts.append(L.demote_headings(content, 2).rstrip())
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def module_entry(s, cfg, version, bundle_dir):
    md = s["metadata"]
    full = render_module(s, cfg, version)
    return {
        "name": s["name"],
        "layer": s["layer"],
        "load": md.get("load"),
        "status": md.get("status"),
        "version": md.get("version", ""),
        "description": s["description"],
        "triggers": md.get("triggers", ""),
        "path": s["rel_dir"],
        "source_url": tree_url(cfg, s["rel_dir"]),
        "bundle_url": f"{raw_base(cfg)}{bundle_dir}/modules/{s['name']}.md",
        "references": s["references"],
        "tokens_skill": L.estimate_tokens(s["body"]),
        "tokens_bundle": L.estimate_tokens(full),
        "_rendered": full,
    }


def manifest_table(entries):
    rows = ["| module | layer | load | status | ~tokens | triggers | fetch |", "|---|---|---|---|---|---|---|"]
    for e in entries:
        fetch = "embedded below" if e["load"] == "always" else ("none (planned)" if e["status"] == "planned" else f"`{e['bundle_url']}`")
        trig = e["triggers"].replace("|", "/")
        rows.append(f"| `{e['name']}` | {e['layer']} | {e['load']} | {e['status']} | {e['tokens_bundle']} | {trig} | {fetch} |")
    return "\n".join(rows)


def cards(entries):
    out = []
    for e in entries:
        if e["load"] == "always":
            continue
        out.append(f"- **{e['name']}** — {e['description']}")
    return "\n".join(out)




def build_anima_pipeline_pack_entry(cfg):
    packs = (cfg.get("pipeline") or {}).get("pipeline_packs") or {}
    if "anima" not in packs:
        return "No `anima` pipeline pack declared."
    raw = raw_base(cfg)
    url = "{}{}/pipelines/anima.md".format(raw, cfg["bundle_dir"])
    stages = " → ".join(["Gate", "Classifier", "Skeleton", "Protection", "Compressor", "Serializer", "Compiler"])
    return "`{}` · one fetch · stages: {}".format(url, stages)

def pipeline_pack_table(cfg):
    packs = (cfg.get("pipeline") or {}).get("pipeline_packs") or {}
    if not packs:
        return "No pipeline packs declared."
    rows = ["| pack | modules | fetch |", "|---|---|---|"]
    raw = raw_base(cfg)
    bundle_dir = cfg["bundle_dir"]
    for name, modules in packs.items():
        module_list = ", ".join(modules)
        url = "{}{}/pipelines/{}.md".format(raw, bundle_dir, name)
        rows.append("| `{}` | {} | `{}` · 1 fetch |".format(name, module_list, url))
    return "\n".join(rows)

def render_pipeline_pack(name, module_names, by_name, cfg, version):
    lines = [
        GEN_NOTE,
        "# PIPELINE PACK: {} · harness v{}".format(name, version),
        "",
        "This generated Web-first pack loads all declared stages in one fetch.",
        "The declared order is authoritative; do not skip, reorder, or replace stages with memory.",
        "",
    ]
    for module_name in module_names:
        if module_name not in by_name:
            raise SystemExit("pipeline pack {}: unknown module {}".format(name, module_name))
        lines.extend([
            "--- MODULE {} ---".format(module_name),
            "",
            L.demote_headings(by_name[module_name]["_rendered"], 1).rstrip(),
            "",
        ])
    return "\n".join(lines).rstrip() + "\n"

def render_kernel(root, cfg, version, entries):
    text = open(os.path.join(root, cfg["kernel"]), encoding="utf-8").read()
    handshake = cfg["handshake"].format(version=version, modules=len(entries))
    subs = {
        "{{VERSION}}": version,
        "{{BUILD_DATE}}": L.today(),
        "{{MODULE_COUNT}}": str(len(entries)),
        "{{HANDSHAKE}}": handshake,
        "{{RAW_BASE}}": raw_base(cfg),
        "{{MANIFEST_TABLE}}": manifest_table(entries) + "\n\n### Module cards (contracts for on-demand modules; use only if a fetch fails)\n\n" + cards(entries),
        "{{PIPELINE_PACK_TABLE}}": pipeline_pack_table(cfg),
        "{{ANIMA_PIPELINE_PACK_ENTRY}}": build_anima_pipeline_pack_entry(cfg),
    }
    for k, v in subs.items():
        text = text.replace(k, v)
    return text, handshake


def render_harness(root, cfg, version, skills, entries, full=False):
    kernel, handshake = render_kernel(root, cfg, version, entries)
    by_name = {s["name"]: s for s in skills}
    lines = [
        GEN_NOTE,
        f"# {cfg['name']} · HARNESS {'FULL ' if full else ''}v{version}",
        "",
        f"> Built {L.today()} from https://github.com/{cfg['repo']} ({cfg['branch']}). "
        + ("This file contains the kernel, the module index, and EVERY module with all references. Nothing else needs to be fetched."
           if full else
           "This file contains the kernel, the module index, and the ALWAYS-ON modules. On-demand modules are fetched from the URLs in the index when the router selects them."),
        "> Read everything, then follow KERNEL §1 (handshake). Do not summarize this file.",
        "",
        "---",
        "",
        L.demote_headings(kernel, 1).rstrip(),
        "",
        "---",
        "",
        "## ALWAYS-ON MODULES" if not full else "## ALL MODULES",
        "",
    ]
    if full:
        for e in entries:
            if e["status"] == "planned":
                continue
            lines.append(L.demote_headings(e["_rendered"], 1).rstrip())
            lines.append("")
            lines.append("---")
            lines.append("")
    else:
        for name, files in cfg["always_on"].items():
            s = by_name[name]
            lines.append(L.demote_headings(render_module(s, cfg, version, only_files=files), 1).rstrip())
            lines.append("")
            lines.append("---")
            lines.append("")
    lines.append(f"## END OF HARNESS — now reply with the handshake line: `{handshake}`")
    lines.append("")
    return "\n".join(lines)


def render_registry(cfg, version, entries):
    rows = ["| Skill | Layer | Load | Status | Purpose | Triggers |", "|---|---|---|---|---|---|"]
    for e in entries:
        purpose = e["description"].split(". ")[0].rstrip(".")
        rows.append(f"| `{e['name']}` | {e['layer']} | {e['load']} | {e['status']} | {purpose} | {e['triggers'].replace('|', '/')} |")
    return "\n".join([
        GEN_NOTE,
        "# Skill Registry",
        "",
        f"Generated from frontmatter by `scripts/build.py` · harness v{version} · {len(entries)} modules. The same data drives KERNEL §5 and `bundle/manifest.json`. To change a row, edit that skill's `SKILL.md` frontmatter and rebuild.",
        "",
        *rows,
        "",
        "## Routing principle",
        "",
        "One skill, one responsibility. Taste lives in `personal-identity-profile` only. Creative decisions are made in `aesthetic-director-core` and expanded by the design skills. Adapters translate; they never design. Feedback goes through `evaluation-loop`, which decides which layer owns the fix.",
        "",
    ])


# ---------- outputs ----------

def build_outputs(root):
    cfg, version, skills = collect(root)
    bundle_dir = cfg["bundle_dir"]
    entries = [module_entry(s, cfg, version, bundle_dir) for s in skills]
    outputs = {}
    for e in entries:
        outputs[f"{bundle_dir}/modules/{e['name']}.md"] = GEN_NOTE + "\n" + e["_rendered"]
    by_name = {e["name"]: e for e in entries}
    for pack_name, module_names in ((cfg.get("pipeline") or {}).get("pipeline_packs") or {}).items():
        pack_parts = [GEN_NOTE, f"# PIPELINE PACK: {pack_name} · harness v{version}", "",
                      "This generated Web-first pack loads all declared stages in one fetch.",
                      "The declared order is authoritative; do not skip, reorder, or replace stages with memory.", ""]
        for module_name in module_names:
            if module_name not in by_name:
                raise SystemExit(f"pipeline pack {pack_name}: unknown module {module_name}")
            pack_parts.append(f"--- MODULE {module_name} ---")
            pack_parts.append("")
            pack_parts.append(L.demote_headings(by_name[module_name]["_rendered"], 1).rstrip())
            pack_parts.append("")
        outputs[f"{bundle_dir}/pipelines/{pack_name}.md"] = "\n".join(pack_parts).rstrip() + "\n"
    outputs[f"{bundle_dir}/HARNESS.md"] = render_harness(root, cfg, version, skills, entries, full=False)
    outputs[f"{bundle_dir}/HARNESS-FULL.md"] = render_harness(root, cfg, version, skills, entries, full=True)
    manifest = {
        "name": cfg["name"],
        "version": version,
        "repo": cfg["repo"],
        "branch": cfg["branch"],
        "raw_base": raw_base(cfg),
        "harness_url": f"{raw_base(cfg)}{bundle_dir}/HARNESS.md",
        "harness_full_url": f"{raw_base(cfg)}{bundle_dir}/HARNESS-FULL.md",
        "handshake": cfg["handshake"].format(version=version, modules=len(entries)),
        "core_tokens": L.estimate_tokens(outputs[f"{bundle_dir}/HARNESS.md"]),
        "full_tokens": L.estimate_tokens(outputs[f"{bundle_dir}/HARNESS-FULL.md"]),
        "pipeline": cfg.get("pipeline", {}),
        "pipeline_packs": {
            name: {
                "modules": module_names,
                "fetches_as": 1,
                "bundle_url": f"{raw_base(cfg)}{bundle_dir}/pipelines/{name}.md",
            }
            for name, module_names in ((cfg.get("pipeline") or {}).get("pipeline_packs") or {}).items()
        },
        "modules": [{k: v for k, v in e.items() if not k.startswith("_")} for e in entries],
    }
    outputs[f"{bundle_dir}/manifest.json"] = json.dumps(manifest, ensure_ascii=False, indent=2) + "\n"
    outputs["docs/skill-registry.md"] = render_registry(cfg, version, entries)
    return cfg, manifest, outputs


def _normalize(text):
    # ignore the build date so a rebuild on another day is not "stale" by itself
    import re
    return re.sub(r"(built|Built) \d{4}-\d{2}-\d{2}", r"\1 DATE", text).replace("\r\n", "\n")


def stale_outputs(root):
    _, _, outputs = build_outputs(root)
    stale = []
    expected_packs = {os.path.basename(k) for k in outputs if k.startswith(f"{cfg['bundle_dir']}/pipelines/")}
    for fn in os.listdir(pipe_dir):
        if fn.endswith(".md") and fn not in expected_packs:
            os.remove(os.path.join(pipe_dir, fn))
            print(f"  removed orphan pipeline pack {fn}")
    for rel, content in outputs.items():

        p = os.path.join(root, rel)
        if not os.path.exists(p):
            stale.append(rel)
            continue
        if _normalize(open(p, encoding="utf-8").read()) != _normalize(content):
            stale.append(rel)
    # orphaned generated bundles (skill/pipeline pack renamed or removed)
    cfg = L.load_config(root)
    mod_dir = os.path.join(root, cfg["bundle_dir"], "modules")
    if os.path.isdir(mod_dir):
        expected = {os.path.basename(k) for k in outputs if k.startswith(f"{cfg['bundle_dir']}/modules/")}
        for fn in os.listdir(mod_dir):
            if fn.endswith(".md") and fn not in expected:
                stale.append(f"{cfg['bundle_dir']}/modules/{fn} (orphan — delete)")
    pipe_dir = os.path.join(root, cfg["bundle_dir"], "pipelines")
    if os.path.isdir(pipe_dir):
        expected = {os.path.basename(k) for k in outputs if k.startswith(f"{cfg['bundle_dir']}/pipelines/")}
        for fn in os.listdir(pipe_dir):
            if fn.endswith(".md") and fn not in expected:
                stale.append(f"{cfg['bundle_dir']}/pipelines/{fn} (orphan — delete)")
    return stale


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    root = L.repo_root(args[0] if args else None)
    if "--check" in sys.argv:
        stale = stale_outputs(root)
        if stale:
            print("stale generated files:")
            for s in stale:
                print("  ", s)
            sys.exit(1)
        print("bundle is up to date")
        return
    cfg, manifest, outputs = build_outputs(root)
    mod_dir = os.path.join(root, cfg["bundle_dir"], "modules")
    pipe_dir = os.path.join(root, cfg["bundle_dir"], "pipelines")
    os.makedirs(mod_dir, exist_ok=True)
    os.makedirs(pipe_dir, exist_ok=True)
    expected = {os.path.basename(k) for k in outputs if k.startswith(f"{cfg['bundle_dir']}/modules/")}
    for fn in os.listdir(mod_dir):
        if fn.endswith(".md") and fn not in expected:
            os.remove(os.path.join(mod_dir, fn))
            print(f"  removed orphan {fn}")
    for rel, content in outputs.items():
        p = os.path.join(root, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        print(f"  wrote {rel} (~{L.estimate_tokens(content)} tokens)")
    core = manifest["core_tokens"]
    budget = cfg.get("core_budget_tokens", 40000)
    flag = "OK" if core <= budget else f"OVER BUDGET ({budget}) — trim harness.json always_on"
    print(f"\nharness v{manifest['version']} · {len(manifest['modules'])} modules · core ≈{core} tokens [{flag}] · full ≈{manifest['full_tokens']} tokens")
    print(f"handshake: {manifest['handshake']}")


if __name__ == "__main__":
    main()
